#ifndef __DOT_RENDERERCONFIG_H_HEADER_GUARD__
#define __DOT_RENDERERCONFIG_H_HEADER_GUARD__

#include "core/PlatformConfig.h"

#ifndef DOT_RENDERER_OPENGL
#define DOT_RENDERER_OPENGL (DOT_PLATFORM_OSX || DOT_PLATFORM_WINDOWS ? 1 : 0)
#endif

#ifndef DOT_RENDERER_OPENGL_TARGET_VERSION
#define DOT_RENDERER_OPENGL_TARGET_VERSION 45
#endif

#if DOT_RENDERER_OPENGL
#	if DOT_RENDERER_OPENGL_TARGET_VERSION >= 31 && DOT_RENDERER_OPENGL_TARGET_VERSION <= 33
#		if DOT_RENDERER_OPENGL_TARGET_VERSION == 31
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 3.1"
#		elif DOT_RENDERER_OPENGL_TARGET_VERSION == 32
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 3.2"
#		else
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 3.3"
#		endif
#	elif DOT_RENDERER_OPENGL_TARGET_VERSION >= 40 && DOT_RENDERER_OPENGL_TARGET_VERSION <= 45
#		if DOT_RENDERER_OPENGL_TARGET_VERSION == 40
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.0"
#		elif DOT_RENDERER_OPENGL_TARGET_VERSION == 41
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.1"
#		elif DOT_RENDERER_OPENGL_TARGET_VERSION == 42
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.2"
#		elif DOT_RENDERER_OPENGL_TARGET_VERSION == 43
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.3"
#		elif DOT_RENDERER_OPENGL_TARGET_VERSION == 44
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.4"
#		else
#			define DOT_RENDERER_OPENGL_NAME "OpenGL 4.5"
#		endif
#	else
#		define DOT_RENDERER_OPENGL_NAME "OpenGL 2.1"
#	endif
#endif

#endif // __DOT_RENDERERCONFIG_H_HEADER_GUARD__